In [7]:
import pandas as pd
import numpy as np

In [9]:
data = pd.read_csv('play_tennis.csv')

In [11]:
data.drop(columns=['day'],inplace=True)

In [13]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [ ]:
# Training 

# Lookup Table

# Testing

In [21]:
print('py =', 9/14)
print('pn = ',5/14)

py = 0.6428571428571429
pn =  0.35714285714285715

In [23]:
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [117]:
Pon =0/5
Prn = 2/5
Psn = 3/5

Poy =4/9
Pry = 3/9
Psy = 2/9

In [119]:
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [121]:
Pcn = 1/5
Phn = 2/5
Pmn = 2/5

Pcy = 3/9
Photy = 2/9
Pmy = 4/9

In [123]:
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [125]:

Phighn = 4/5
Pnn = 1/5


Phy = 3/9
Pny = 6/9

In [127]:
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [129]:

Psn = 3/5
Pwn = 2/5


Pstrongy = 3/9
Pweaky = 6/9

In [131]:
# Outlook=sunny, Temp=Hot , Humidity=high , Wind = weak

Pyes = py*Photy* Psy * Phy *Pweaky #
#P=(py = 9/14*Psy = 3/5*Photy = 2/9*Phy = 3/9*Pweaky = 6/9)
#print(P)
print(Pyes)

0.007054673721340388

In [107]:
Pno =pn* Psn* Phn*Phighn*Pwn
print(Pno)

0.02742857142857143

In [133]:
# so no play from Pno